import './images/feature1.png'
import './images/feature2.png'
import './images/feature3.png'
import './images/feature4.png'

import './css/warehouse.css'
import './css/warehouse-header.css'
import './css/warehouse-description.css'
import './css/warehouse-help.css'
import './css/warehouse-features.css'
import './css/warehouse-testimonials.css'
// import './css/warehouse-enemies.css'
// import './css/warehouse-life.css'
// import './css/warehouse-chat.css'
// import './css/warehouse-register.css'